services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4567:4567"
    environment:
      ConnectionStrings__EFDB: "${EFDB_CONNECTION_STRING}"
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: "4567"
